# A Makefile for the FbDK.  This Makefile is broken into a series of related
# pieces, each of which appears in the makefiles/ subdirectory.  This file
# should only contain includes and those details which must be specified at top
# level.

.PHONY: default
default: all

# Utilities used by this Makefile.
include makefiles/utils.make

# Instructions to build interpreters
include makefiles/interpreters.make
